apiVersion: apps/v1 # specify version of k8s api which allows certains objects to be declared in this file
kind: Deployment # specify what of object is used in this file Pod | Service | Deployment etc.,
metadata:
  name: client-deployment #name of this container
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web 
        # custom labels are created, through this other k8s object refers this object, ex - yuvaraj: goodboy
    spec:
      containers:
        - name: client #name of the container
          image: stephengrider/multi-client #name of the image to be pulled from docker-hub
          ports:
            - containerPort: 3000 # though this port this container output could be accessed