apiVersion: v1
kind: Service # manages the network inside cluster
metadata:
  name: client-node-port #Name of this container
spec:
  type: NodePort # should be used only in local as customers does not access our site with port.
  ports:
    - port: 3050 # through this port any other object will connect through this container
      targetPort: 3000 # opens the port of this container to specific port (3000)
      nodePort: 31515 # this is entry point port of this container
  selector:
    component: web # find labels specified in other object and establish connection through port specified in targetPort